-- MySQL Script generated by MySQL Workbench
-- dom 28 feb 2021 22:17:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema food-com-recipes-and-interactions
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food-com-recipes-and-interactions
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food-com-recipes-and-interactions` DEFAULT CHARACTER SET utf16 ;
USE `food-com-recipes-and-interactions` ;

-- -----------------------------------------------------
-- Table `food-com-recipes-and-interactions`.`PP_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-com-recipes-and-interactions`.`PP_users` (
  `u` INT NOT NULL,
  `techniques` TEXT NOT NULL,
  `items` TEXT NOT NULL,
  `n_items` TEXT NOT NULL,
  `ratings` TEXT NOT NULL,
  `n_ratings` INT NOT NULL,
  PRIMARY KEY (`u`),
  UNIQUE INDEX `u` (`u` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16;


-- -----------------------------------------------------
-- Table `food-com-recipes-and-interactions`.`interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-com-recipes-and-interactions`.`interactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `rating` INT NOT NULL,
  `u` INT NOT NULL,
  `i` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interactions_PP_users_idx` (`u` ASC) VISIBLE,
  CONSTRAINT `fk_interactions_PP_users`
    FOREIGN KEY (`u`)
    REFERENCES `food-com-recipes-and-interactions`.`PP_users` (`u`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16;


-- -----------------------------------------------------
-- Table `food-com-recipes-and-interactions`.`raw_interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-com-recipes-and-interactions`.`raw_interactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `recipe_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `rating` INT NOT NULL,
  `review` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16;


-- -----------------------------------------------------
-- Table `food-com-recipes-and-interactions`.`raw_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-com-recipes-and-interactions`.`raw_recipe` (
  `name` VARCHAR(100) NOT NULL,
  `id` INT NOT NULL,
  `minutes` INT NOT NULL,
  `contributor_id` INT NOT NULL,
  `tags` TEXT NOT NULL,
  `nutrition` TEXT NOT NULL,
  `submitted` DATE NOT NULL,
  `n_steps` INT NOT NULL,
  `steps` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `ingredients` TEXT NOT NULL,
  `n_ingredients` INT NOT NULL,
  `i` INT NULL DEFAULT NULL,
  `name_tokens` TEXT NULL DEFAULT NULL,
  `ingredient_tokens` TEXT NULL DEFAULT NULL,
  `steps_tokens` TEXT NULL DEFAULT NULL,
  `techniques` TEXT NULL DEFAULT NULL,
  `calorie_level` INT NULL DEFAULT NULL,
  `ingredient_ids` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16;


-- -----------------------------------------------------
-- Table `food-com-recipes-and-interactions`.`raw_recipe_has_raw_interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food-com-recipes-and-interactions`.`raw_recipe_has_raw_interactions` (
  `raw_recipe_id` INT NOT NULL,
  `raw_interactions_id` INT NOT NULL,
  PRIMARY KEY (`raw_recipe_id`, `raw_interactions_id`),
  INDEX `fk_raw_recipe_has_raw_interactions_raw_interactions1_idx` (`raw_interactions_id` ASC) VISIBLE,
  INDEX `fk_raw_recipe_has_raw_interactions_raw_recipe1_idx` (`raw_recipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_raw_recipe_has_raw_interactions_raw_recipe1`
    FOREIGN KEY (`raw_recipe_id`)
    REFERENCES `food-com-recipes-and-interactions`.`raw_recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_raw_recipe_has_raw_interactions_raw_interactions1`
    FOREIGN KEY (`raw_interactions_id`)
    REFERENCES `food-com-recipes-and-interactions`.`raw_interactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
